env:
  node: true

extends:
  - ../.eslintrc.yml

overrides:
  - files:
    - config/**/*
    - src/data/migrations/**/*
    rules:
      '@typescript-eslint/no-var-requires':
        - off
rules:
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
